urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.views import login, logout
from maths.centres.views import welcome
from maths.cat_test.views import start_test, question, feedback, end_test

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', welcome, name='home'),
    # url(r'^maths/', include('maths.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^accounts/login/$',  login,  {'extra_context':{'next': '/welcome/'}}),
    (r'^accounts/logout/$', logout),
    (r'^welcome/$', welcome),
    (r'^start/$', start_test),
    (r'^question/$', question),    
    (r'^feedback/$', feedback),
    (r'^end/$', end_test),
)

centres/models.py
from django.db import models
from django.contrib.auth.models import User
from item_banks.models import ItemBank, Threshold
import datetime

# Create your models here.
class Centre(models.Model):
  name =  models.CharField(max_length=255)
  centre_id = models.CharField(max_length=5)
  create_date = models.DateTimeField()
  
  def __unicode__(self):
    return self.centre_id + " " + self.name  

class Candidate(models.Model):
  gender =  models.CharField(max_length=1)
  dob = models.DateField()
  centre = models.ForeignKey(Centre)
  user = models.OneToOneField(User)   
    
  def __unicode__(self):
    return self.user.first_name + " " + self.user.last_name
    
class UserItemBank(models.Model):
  user = models.ForeignKey(User)
  item_bank = models.ForeignKey(ItemBank)
  tests = models.IntegerField(default=0)    
  questions = models.IntegerField(default=0)
  correct = models.IntegerField(default=0)
  time_taken = models.IntegerField(default=0)
  time_taken_str = models.CharField(max_length=8,default='00:00:00')  
  ability = models.FloatField(default=0)
  ability_stand_dev = models.FloatField(default=1)
  grade = models.IntegerField(default=0)    
  
  def update(self,user_cat_test):
    self.tests += 1
    self.questions += user_cat_test.items
    self.correct += user_cat_test.right
    self.time_taken += user_cat_test.time_taken
    self.ability = user_cat_test.ability
    self.ability_stand_dev = user_cat_test.stand_dev     
    user_cat_test.updateTime()
    self.time_taken += user_cat_test.time_taken
    self.time_taken_str = str(datetime.timedelta(seconds=self.time_taken))
    self.save()
    return(self)
    
  def probabilities(self):
    #Return grade thresholds  
    threshes = Threshold.objects.filter(item_bank=self.item_bank)
    #For each threshold initialise UserItemBankProbabilities
    for thresh in threshes:
      prob = UserItemBankProbabilities()
      prob.user_item_bank = self
      prob.threshold = thresh
      prob.probability = thresh.init_prob
      prob.save()      
    return(self)    

class UserItemBankProbabilities(models.Model):
    user_item_bank = models.ForeignKey(UserItemBank)
    threshold = models.ForeignKey(Threshold)
    probability = models.FloatField()      

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Adaptive Mathematics{% endblock %}</title>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/end_test.html
{% extends "base.html" %}

{% block content %}

<BR>
<font color = "red">{{error}}</font>
<BR>

Ability: {{user_cat_test.ability|floatformat:3}}<BR>

Standard Deviation: {{user_cat_test.stand_dev|floatformat:3}}<BR>

Probabilities<BR>
{% for prob in probs %}
{{prob.threshold.grade.name}} : {{prob.probability|floatformat:0}}%<BR>
{% endfor %}

The End

<A href="/welcome/">Return</A>

{% endblock %}

templates/feedback.html
{% extends "base.html" %}

{% block content %}

Feedback<BR>

{% if cat_test_item.correct == 1 %}

  Correct!<BR>

{% else %}

  Wrong!<BR>

{% endif %}

Time taken: {{cat_test_item.time_taken}}<BR>

Your response was:

{{response|safe|escape}}

<BR>

The answer was:

{{answer|safe|escape}}

<BR>

{% if user_cat_test.in_a_row > 1 %}

{{user_cat_test.in_a_row}} in a row!<BR>
 
{% endif %} 
 
Ability: {{ user_cat_test.ability|floatformat:3 }}<BR>

Probabilities<BR>
{% for prob in probs %}
{{prob.threshold.grade.name}} : {{prob.probability|floatformat:0}}%<BR>
{% endfor %}

{% if end_test == 1 %}
  <A href="/end/">End</A>
{% else %}  
  <A href="/question/">Next</A>
{% endif %}

{% endblock %}

templates/fractions.html
<style>
    td.upper_line { border-top:solid 1px black; }
    table.fraction { text-align: right; vertical-align: middle;
        margin-top:0.5em; margin-bottom:0.5em; line-height: 2em; }
</style>

Fraction Question<BR>

Work out:
<BR>
{{question.f1|safe|escape }} {{question.oper}} {{ question.f2|safe|escape }}
<BR>

<form id="fForm" action="" autocomplete="off" method="post">{% csrf_token %}
	<table class="fraction" cellpadding="0">
		<tr>
			<td rowspan="2" nowrap="nowrap">
				{{ form.const }}
			</td>
			<td nowrap="nowrap">
				{{ form.num }}
			</td>
		</tr>
		<tr>
			<td class="upper_line">
				{{ form.denom }}
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="hidden" id="timer_fm" name="time"/>
			</td>
		</tr>
		<tr>
			<td colspan="2"><input type="submit" id="fm_button" value="Send answer" />
			</td>
		</tr>
	</table>
</form>

<BR>Make sure you write the fraction in its simplest form. 

templates/question.html
{% extends "base.html" %}

{% block content %}

<script>
$(document).ready(function(){
   x = 0;
   window.setInterval(timer, 1000);
});
 
function timer() {
  x ++;
  $('#timer_fm').val(x);   
}
</script>

{{user_cat_test.item_bank.domain.name}}<BR>
{{user_cat_test.item_bank.name}}<BR>
{{user_cat_test.item_bank.topic}}<BR>

Questions completed: {{user_cat_test.items}}<BR>

{% include user_cat_test.item_bank.template.name %}
	
{% endblock %}

templates/start_test.html
{% extends "base.html" %}

{% block content %}

Start Test

You are about to take a test.<BR>

Domain: {{item_bank.domain.name}}<BR>
Topic: {{item_bank.name}}<BR>
Area: {{item_bank.topic}}<BR>

The test is a {{cat_test.name}}<BR>
with a minimum of {{cat_test.min_items}} questions<BR>
and a maximum of {{cat_test.max_items}} questions<BR>

Take as long as you like, there is no time limit.

<A href="/question/">Start the test</A>

{% endblock %}

templates/user_item_banks.html
{% extends "base.html" %}

{% block content %}

Welcome!
<BR>

<h3>Item Banks</h3>

<table>
<th>Domain</th>
<th>Name</th>
<th>Topic</th>
<th>Questions Answered</th>
<th>Time Spent</th>
<th>Ability</th>
{% for bank in user_banks %}
	{% for thresh in bank.useritembankprobabilities_set.all %}
		<th>{{thresh.threshold.grade.name}}<th>
	{% endfor %}
{% endfor %}

{% for cat_test in cat_tests %}  
  <th>Test</th>
{% empty %}
    
{% endfor %}

{% for bank in user_banks %}

<tr>
  <td>{{bank.item_bank.domain}}</td>
  <td>{{bank.item_bank.name}}</td>
  <td>{{bank.item_bank.topic}}</td>
  <td>{{bank.questions}}</td>
  <td>{{bank.time_taken_str}}</td>
  <td>{{bank.ability|floatformat:3}}</td>
  
{% for thresh in bank.useritembankprobabilities_set.all %}
  <td>{{thresh.probability|floatformat:0}}%<td>
{% endfor %}
  
{% for cat_test in cat_tests %}  
  <td><A href="/start/?item_bank_id={{bank.item_bank.id}}&cat_test_id={{cat_test.id}}">{{cat_test.name}}</A></td>
{% empty %}  
{% endfor %}
  
</tr>
{% empty %}
Sorry, no item banks assigned to this user
{% endfor %}
</table>

{% endblock %}